---
# vars file for coupa
download_url: http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz
download_folder: /opt
java_name: "{{download_folder}}/jdk1.8.0_191"
java_archive: "{{download_folder}}/jdk-8u191-linux-x64.tar.gz"
