FROM centos:7

RUN yum -y install wget

RUN wget -O /tmp/epel-release-7-11.noarch.rpm https://rpmfind.net/linux/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

RUN rpm -ivh /tmp/epel-release-7-11.noarch.rpm

RUN yum -y install nginx

COPY coupa.conf /etc/nginx/conf.d/coupa.conf

CMD service nginx restart


